const POLLING_TIMEOUT_SECONDS = 10;

const POLLING_BASE_RETRY_DELAY_MS = 2000;
const POLLING_MAX_RETRY_DELAY_MS = 30000;

const UPDATE_MAX_ATTEMPTS = 3;
const UPDATE_RETRY_DELAY_MS = 2000;

// Precisa ser maior que o timeout do long polling.
const TELEGRAM_REQUEST_TIMEOUT_MS = 25000;

module.exports = {
  POLLING_TIMEOUT_SECONDS,
  POLLING_BASE_RETRY_DELAY_MS,
  POLLING_MAX_RETRY_DELAY_MS,
  UPDATE_MAX_ATTEMPTS,
  UPDATE_RETRY_DELAY_MS,
  TELEGRAM_REQUEST_TIMEOUT_MS,
};
