const XP_MIN = 3;
const XP_MAX = 7;

const XP_COOLDOWN = 40 * 1000;

const MIN_MESSAGE_LENGTH = 4;
const DUPLICATE_COOLDOWN = 120000;
const MAX_LEVEL = 50;
const BASE_LEVEL_XP = 400;
const LEVEL_XP_INCREASE = 100;

module.exports = {
  XP_MIN,
  XP_MAX,
  XP_COOLDOWN,
  MIN_MESSAGE_LENGTH,
  DUPLICATE_COOLDOWN,
  MAX_LEVEL,
  BASE_LEVEL_XP,
  LEVEL_XP_INCREASE,
};
